import os
import json
import re

RESULTS_DIR = "results"
REPORT_MD = "实验报告.md"

def load_metrics_from_file(category, mode):
    filename = f"{category}_llm_ranker_{mode.lower()}.json"
    filepath = os.path.join(RESULTS_DIR, filename)
    if os.path.exists(filepath):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data.get("valid", {}), data.get("test", {})
        except Exception as e:
            print(f"Error loading {filepath}: {e}")
    # Default fallbacks
    return {"NDCG@10": 0.0, "Hit@10": 0.0, "MRR@10": 0.0, "eval_time_sec": 0.0}, \
           {"NDCG@10": 0.0, "Hit@10": 0.0, "MRR@10": 0.0, "eval_time_sec": 0.0}

def main():
    categories = ["Industrial_and_Scientific", "Musical_Instruments", "CDs_and_Vinyl"]
    modes = ["zeroshot", "fewshot"]
    
    llm_metrics = {}
    for cat in categories:
        for mode in modes:
            valid_m, test_m = load_metrics_from_file(cat, mode)
            model_key = f"{cat}_LLM_Ranker_{'ZeroShot' if mode == 'zeroshot' else 'FewShot'}"
            llm_metrics[model_key] = {
                "category": cat,
                "model": f"LLM_Ranker_{'ZeroShot' if mode == 'zeroshot' else 'FewShot'}",
                "valid": valid_m,
                "test": test_m
            }
            print(f"Loaded {model_key}: valid NDCG={valid_m.get('NDCG@10', 0):.4f}, test NDCG={test_m.get('NDCG@10', 0):.4f}")

    # 1. 更新 all_results.json
    all_results_path = os.path.join(RESULTS_DIR, "all_results.json")
    if os.path.exists(all_results_path):
        with open(all_results_path, "r", encoding="utf-8") as f:
            all_results = json.load(f)
    else:
        all_results = {}
        
    for k, v in llm_metrics.items():
        all_results[k] = v
        print(f"Updated all_results.json with {k}")
        
    with open(all_results_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False)
    print("Successfully updated all_results.json!")

    # 2. 更新 dashboard_data.js
    js_path = os.path.join(RESULTS_DIR, "dashboard_data.js")
    if os.path.exists(js_path):
        with open(js_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        prefix = "const DASHBOARD_DATA = "
        if prefix in content:
            idx = content.find(prefix)
            json_part = content[idx + len(prefix):].strip()
            if json_part.endswith(";"):
                json_part = json_part[:-1].strip()
            
            db_data = json.loads(json_part)
            
            # Dynamically update dashboard_data
            for cat in categories:
                # Zero-shot
                zs_test = llm_metrics[f"{cat}_LLM_Ranker_ZeroShot"]["test"]
                db_data["metrics"][cat]["LLM Zero-Shot"] = {
                    "NDCG": round(zs_test.get("NDCG@10", 0.0), 4),
                    "Hit": round(zs_test.get("Hit@10", 0.0), 4),
                    "MRR": round(zs_test.get("MRR@10", 0.0), 4)
                }
                # Few-shot
                fs_test = llm_metrics[f"{cat}_LLM_Ranker_FewShot"]["test"]
                db_data["metrics"][cat]["LLM Few-Shot"] = {
                    "NDCG": round(fs_test.get("NDCG@10", 0.0), 4),
                    "Hit": round(fs_test.get("Hit@10", 0.0), 4),
                    "MRR": round(fs_test.get("MRR@10", 0.0), 4)
                }
            
            with open(js_path, "w", encoding="utf-8") as f:
                f.write("/* Auto-generated by update_llm_metrics.py */\n")
                f.write("const DASHBOARD_DATA = ")
                json.dump(db_data, f, indent=2, ensure_ascii=False)
                f.write(";\n")
            print("Successfully updated dashboard_data.js!")

    # 3. 更新 实验报告.md
    if os.path.exists(REPORT_MD):
        with open(REPORT_MD, "r", encoding="utf-8") as f:
            md_content = f.read()
            
        # 4.1 主要结果表格替换 (Test NDCG@10)
        ind_zs = llm_metrics["Industrial_and_Scientific_LLM_Ranker_ZeroShot"]["test"].get("NDCG@10", 0.0)
        mus_zs = llm_metrics["Musical_Instruments_LLM_Ranker_ZeroShot"]["test"].get("NDCG@10", 0.0)
        cds_zs = llm_metrics["CDs_and_Vinyl_LLM_Ranker_ZeroShot"]["test"].get("NDCG@10", 0.0)
        mean_zs = (ind_zs + mus_zs + cds_zs) / 3.0
        
        ind_fs = llm_metrics["Industrial_and_Scientific_LLM_Ranker_FewShot"]["test"].get("NDCG@10", 0.0)
        mus_fs = llm_metrics["Musical_Instruments_LLM_Ranker_FewShot"]["test"].get("NDCG@10", 0.0)
        cds_fs = llm_metrics["CDs_and_Vinyl_LLM_Ranker_FewShot"]["test"].get("NDCG@10", 0.0)
        mean_fs = (ind_fs + mus_fs + cds_fs) / 3.0
        
        pattern_zs = r"\|\s*\*\*LLM Zero-Shot\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|[^|]*\|"
        pattern_fs = r"\|\s*\*\*LLM Few-Shot\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|[^|]*\|"
        
        new_zs_row = f"| **LLM Zero-Shot** | {ind_zs:.4f} | {mus_zs:.4f} | {cds_zs:.4f} | {mean_zs:.4f} |"
        new_fs_row = f"| **LLM Few-Shot** | {ind_fs:.4f} | {mus_fs:.4f} | {cds_fs:.4f} | {mean_fs:.4f} |"
        
        md_content = re.sub(pattern_zs, new_zs_row, md_content)
        md_content = re.sub(pattern_fs, new_fs_row, md_content)
        
        # 4.2 详细结果表格替换
        sections = [
            ("Industrial_and_Scientific", "Industrial_and_Scientific"),
            ("Musical_Instruments", "Musical_Instruments"),
            ("CDs_and_Vinyl", "CDs_and_Vinyl")
        ]
        
        for cat_name, cat_key in sections:
            zs_test = llm_metrics[f"{cat_key}_LLM_Ranker_ZeroShot"]["test"]
            zs_ndcg = zs_test.get("NDCG@10", 0.0)
            zs_hit = zs_test.get("Hit@10", 0.0)
            zs_mrr = zs_test.get("MRR@10", 0.0)
            
            fs_test = llm_metrics[f"{cat_key}_LLM_Ranker_FewShot"]["test"]
            fs_ndcg = fs_test.get("NDCG@10", 0.0)
            fs_hit = fs_test.get("Hit@10", 0.0)
            fs_mrr = fs_test.get("MRR@10", 0.0)
            
            sec_start = md_content.find(f"**{cat_name}：**")
            if sec_start != -1:
                sec_end = md_content.find("**", sec_start + 10)
                if sec_end == -1:
                    sec_end = len(md_content)
                
                sec_block = md_content[sec_start:sec_end]
                
                sec_block = re.sub(r"\|\s*LLM Zero-Shot\s*\|[^|]*\|[^|]*\|[^|]*\|", 
                                   f"| LLM Zero-Shot | {zs_ndcg:.4f} | {zs_hit:.4f} | {zs_mrr:.4f} |", sec_block)
                sec_block = re.sub(r"\|\s*LLM Few-Shot\s*\|[^|]*\|[^|]*\|[^|]*\|", 
                                   f"| LLM Few-Shot | {fs_ndcg:.4f} | {fs_hit:.4f} | {fs_mrr:.4f} |", sec_block)
                
                md_content = md_content[:sec_start] + sec_block + md_content[sec_end:]
                print(f"Updated Section 4.2 detailed table for {cat_name}")

        # 4.3 验证集结果表格替换
        ind_zs_v = llm_metrics["Industrial_and_Scientific_LLM_Ranker_ZeroShot"]["valid"].get("NDCG@10", 0.0)
        mus_zs_v = llm_metrics["Musical_Instruments_LLM_Ranker_ZeroShot"]["valid"].get("NDCG@10", 0.0)
        cds_zs_v = llm_metrics["CDs_and_Vinyl_LLM_Ranker_ZeroShot"]["valid"].get("NDCG@10", 0.0)
        
        ind_fs_v = llm_metrics["Industrial_and_Scientific_LLM_Ranker_FewShot"]["valid"].get("NDCG@10", 0.0)
        mus_fs_v = llm_metrics["Musical_Instruments_LLM_Ranker_FewShot"]["valid"].get("NDCG@10", 0.0)
        cds_fs_v = llm_metrics["CDs_and_Vinyl_LLM_Ranker_FewShot"]["valid"].get("NDCG@10", 0.0)
        
        pattern_zs_v = r"\|\s*\*\*LLM Zero-Shot\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|"
        pattern_fs_v = r"\|\s*\*\*LLM Few-Shot\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|"
        
        new_zs_v_row = f"| **LLM Zero-Shot** | {ind_zs_v:.4f} | {mus_zs_v:.4f} | {cds_zs_v:.4f} |"
        new_fs_v_row = f"| **LLM Few-Shot** | {ind_fs_v:.4f} | {mus_fs_v:.4f} | {cds_fs_v:.4f} |"
        
        md_content = re.sub(pattern_zs_v, new_zs_v_row, md_content)
        md_content = re.sub(pattern_fs_v, new_fs_v_row, md_content)
        print("Updated Section 4.3 validation table.")
        
        # 5.3 状态表格替换
        old_status_row = r"\|\s*\*\*LLM \(全部类别\)\*\*\s*\|.*\|.*\|"
        new_status_row = "| **LLM (全部类别)** |  已完成 | 成功将 LLM Zero-Shot 与 Few-Shot 重排序评估完整扩展至全部三个数据集，呈现了完整的性能横向对比！ |"
        
        # Try both replacements just in case
        if re.search(old_status_row, md_content):
            md_content = re.sub(old_status_row, new_status_row, md_content)
        else:
            old_status_row_alt = r"\|\s*\*\*LLM \(其他类别\)\*\*\s*\|.*\|.*\|"
            md_content = re.sub(old_status_row_alt, new_status_row, md_content)
            
        with open(REPORT_MD, "w", encoding="utf-8") as f:
            f.write(md_content)
        print("Successfully updated 实验报告.md with dynamic LLM metrics!")

if __name__ == "__main__":
    main()
