import os
import json
import re

RESULTS_DIR = "results"
REPORT_MD = "实验报告.md"

def load_metrics_from_file(category):
    filename = f"{category}_bpr_advanced.json"
    filepath = os.path.join(RESULTS_DIR, filename)
    if os.path.exists(filepath):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data.get("valid", {}), data.get("test", {})
        except Exception as e:
            print(f"Error loading {filepath}: {e}")
    # Default fallbacks
    return {"NDCG@10": 0.0, "Hit@10": 0.0, "MRR@10": 0.0, "eval_time_sec": 0.0}, \
           {"NDCG@10": 0.0, "Hit@10": 0.0, "MRR@10": 0.0, "eval_time_sec": 0.0}

def main():
    categories = ["Industrial_and_Scientific", "Musical_Instruments", "CDs_and_Vinyl"]
    
    bpr_adv_metrics = {}
    for cat in categories:
        valid_m, test_m = load_metrics_from_file(cat)
        model_key = f"{cat}_BPR_Advanced"
        bpr_adv_metrics[model_key] = {
            "category": cat,
            "model": "BPR_Advanced",
            "valid": valid_m,
            "test": test_m
        }
        print(f"Loaded {model_key}: valid NDCG={valid_m.get('NDCG@10', 0):.4f}, test NDCG={test_m.get('NDCG@10', 0):.4f}")

    # 1. 更新 all_results.json
    all_results_path = os.path.join(RESULTS_DIR, "all_results.json")
    if os.path.exists(all_results_path):
        with open(all_results_path, "r", encoding="utf-8") as f:
            all_results = json.load(f)
    else:
        all_results = {}
        
    for k, v in bpr_adv_metrics.items():
        all_results[k] = v
        print(f"Updated all_results.json with {k}")
        
    with open(all_results_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False)
    print("Successfully updated all_results.json!")

    # 2. 更新 dashboard_data.js
    js_path = os.path.join(RESULTS_DIR, "dashboard_data.js")
    if os.path.exists(js_path):
        with open(js_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        prefix = "const DASHBOARD_DATA = "
        if prefix in content:
            idx = content.find(prefix)
            json_part = content[idx + len(prefix):].strip()
            if json_part.endswith(";"):
                json_part = json_part[:-1].strip()
            
            db_data = json.loads(json_part)
            
            # Dynamically update dashboard_data
            for cat in categories:
                test_m = bpr_adv_metrics[f"{cat}_BPR_Advanced"]["test"]
                db_data["metrics"][cat]["BPR_Advanced"] = {
                    "NDCG": round(test_m.get("NDCG@10", 0.0), 4),
                    "Hit": round(test_m.get("Hit@10", 0.0), 4),
                    "MRR": round(test_m.get("MRR@10", 0.0), 4)
				}
            
            with open(js_path, "w", encoding="utf-8") as f:
                f.write("/* Auto-generated by update_bpr_advanced_metrics.py */\n")
                f.write("const DASHBOARD_DATA = ")
                json.dump(db_data, f, indent=2, ensure_ascii=False)
                f.write(";\n")
            print("Successfully updated dashboard_data.js!")

    # 3. 更新 实验报告.md
    if os.path.exists(REPORT_MD):
        with open(REPORT_MD, "r", encoding="utf-8") as f:
            md_content = f.read()
            
        # 4.1 主要结果表格更新
        ind_ndcg = bpr_adv_metrics["Industrial_and_Scientific_BPR_Advanced"]["test"].get("NDCG@10", 0.0)
        mus_ndcg = bpr_adv_metrics["Musical_Instruments_BPR_Advanced"]["test"].get("NDCG@10", 0.0)
        cds_ndcg = bpr_adv_metrics["CDs_and_Vinyl_BPR_Advanced"]["test"].get("NDCG@10", 0.0)
        mean_ndcg = (ind_ndcg + mus_ndcg + cds_ndcg) / 3.0
        
        bpr_adv_row = f"| **BPR_Advanced** | {ind_ndcg:.4f} | {mus_ndcg:.4f} | {cds_ndcg:.4f} | {mean_ndcg:.4f} |"
        
        # Check if BPR_Advanced row is already in the table, otherwise insert it after BPR
        if "| **BPR_Advanced** |" in md_content:
            md_content = re.sub(r"\|\s*\*\*BPR_Advanced\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|[^|]*\|", bpr_adv_row, md_content)
        else:
            bpr_pattern = r"(\|\s*\*\*BPR\*\*\s*🏆?\s*\|[^|]*\|[^|]*\|[^|]*\|[^|]*\|)"
            md_content = re.sub(bpr_pattern, f"\\1\n{bpr_adv_row}", md_content)
            
        # 4.2 详细结果表格更新
        sections = [
            ("Industrial_and_Scientific", "Industrial_and_Scientific"),
            ("Musical_Instruments", "Musical_Instruments"),
            ("CDs_and_Vinyl", "CDs_and_Vinyl")
        ]
        
        for cat_name, cat_key in sections:
            test_m = bpr_adv_metrics[f"{cat_key}_BPR_Advanced"]["test"]
            ndcg = test_m.get("NDCG@10", 0.0)
            hit = test_m.get("Hit@10", 0.0)
            mrr = test_m.get("MRR@10", 0.0)
            
            detail_row = f"| BPR_Advanced | {ndcg:.4f} | {hit:.4f} | {mrr:.4f} |"
            
            sec_start = md_content.find(f"**{cat_name}：**")
            if sec_start != -1:
                sec_end = md_content.find("**", sec_start + 10)
                if sec_end == -1:
                    sec_end = len(md_content)
                
                sec_block = md_content[sec_start:sec_end]
                
                if "| BPR_Advanced |" in sec_block:
                    sec_block = re.sub(r"\|\s*BPR_Advanced\s*\|[^|]*\|[^|]*\|[^|]*\|", detail_row, sec_block)
                else:
                    bpr_det_pattern = r"(\|\s*BPR\s*\|[^|]*\|[^|]*\|[^|]*\|)"
                    sec_block = re.sub(bpr_det_pattern, f"\\1\n{detail_row}", sec_block)
                
                md_content = md_content[:sec_start] + sec_block + md_content[sec_end:]
                print(f"Updated Section 4.2 detailed table for {cat_name}")

        # 4.3 验证集结果表格更新
        ind_ndcg_v = bpr_adv_metrics["Industrial_and_Scientific_BPR_Advanced"]["valid"].get("NDCG@10", 0.0)
        mus_ndcg_v = bpr_adv_metrics["Musical_Instruments_BPR_Advanced"]["valid"].get("NDCG@10", 0.0)
        cds_ndcg_v = bpr_adv_metrics["CDs_and_Vinyl_BPR_Advanced"]["valid"].get("NDCG@10", 0.0)
        
        bpr_adv_v_row = f"| **BPR_Advanced** | {ind_ndcg_v:.4f} | {mus_ndcg_v:.4f} | {cds_ndcg_v:.4f} |"
        
        if "| **BPR_Advanced** |" in md_content[md_content.find("### 4.3 验证集结果"):]:
            # Wait, let's just replace in the file where BPR_Advanced is in validation context
            val_section_start = md_content.find("### 4.3 验证集结果")
            val_section = md_content[val_section_start:]
            val_section = re.sub(r"\|\s*\*\*BPR_Advanced\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|", bpr_adv_v_row, val_section)
            md_content = md_content[:val_section_start] + val_section
        else:
            val_section_start = md_content.find("### 4.3 验证集结果")
            val_section = md_content[val_section_start:]
            bpr_val_pattern = r"(\|\s*\*\*BPR\*\*\s*\|[^|]*\|[^|]*\|[^|]*\|)"
            val_section = re.sub(bpr_val_pattern, f"\\1\n{bpr_adv_v_row}", val_section)
            md_content = md_content[:val_section_start] + val_section
            
        print("Updated Section 4.3 validation table.")
        
        with open(REPORT_MD, "w", encoding="utf-8") as f:
            f.write(md_content)
        print("Successfully updated 实验报告.md with dynamic BPR_Advanced metrics!")

if __name__ == "__main__":
    main()
